### PR TITLE
Adding tokenHandler to options

### PR DESCRIPTION
**Pull request by andriy-bulynko**
Adding tokenHandler to options forwarded to the underlying NATS connection.

### CODE REVIEW

**Comment by andriy-bulynko** [comment]
@aricart: Thanks! Is there any chance you could (at some point) cut a release that includes this change? Thanks in advance!

**Comment by aricart** [comment]
yes early this week, I want to add other changes first.

**Comment by andriy-bulynko** [comment]
@aricart: Awesome - thanks!

**Comment by andriy-bulynko** [comment]
@aricart: The 0.2.4 release from today didn't show up as a release/tag on GitHub, but just as a new version in NPM. Not a big deal obviously, but just wanted to make sure you're aware of it. Thanks again!

**Pull request merged**
